### ISSUE TITLE
Removing 5 or more dimensions from a taylor1+ value causes a double free.

### ISSUE THREAD

**Issue by gavlegoat** [antoinemine/apron#10]
It seems that whenever the last n dimensions are removed from a taylor1+ value, if n >= 5, a double free occurs. For values of n less than 5 there is no error. Here is a minimal example demonstrating the issue: https://gist.github.com/gavlegoat/0b831da823c03355402745d658f4c810

**Comment by kghorbal** [comment]
This should be fixed now (commit 1f4ee11b6b545). 
Thanks for the report!
