### ISSUE TITLE
Opam installation fails on WSL/Ubuntu (v0.9.14 with OCaml 5.1.1)

### ISSUE THREAD

**Issue by MERCEcousineau** [antoinemine/apron#103]
Dear Apron developers, 
I ran into a problem when installing apron v0.9.14 on Ubuntu running on top of WSL (Windows Subsystem for Linux).
This problem does not occur for v0.9.14 on standard Ubuntu and macOS, 
and it does neither occur for v0.9.13 on WSL/Ubuntu and standard Ubuntu.
 
It seems to be a permissions problem for some directory called "shared".
Attached are the opam info/env/log files.

Thanks

[apron-2154-d0f245.env.txt](https://github.com/antoinemine/apron/files/14836970/apron-2154-d0f245.env.txt)
[apron-2154-d0f245.info.txt](https://github.com/antoinemine/apron/files/14836971/apron-2154-d0f245.info.txt)
[apron-2154-d0f245.out.txt](https://github.com/antoinemine/apron/files/14836972/apron-2154-d0f245.out.txt)

**Comment by MERCEcousineau** [comment]
After digging a little bit, I found that there is no C++ compiler by default in WSL/Ubuntu.
(compilation was failing in ./ppl because $(CXX) was expanded to an empty string).

I'm pretty sure I did not get an Opam warning concerning an external dependency (sorry if I missed it).
I did not get any warning when running ./configure manually.

I could install apron via opam after installing g++ via apt and export CXX=g++

**Comment by MERCEcousineau** [comment]
P.S: I could not figure why I got some "permission denied" error when opam installation failed at first

**Comment by antoinemine** [comment]
Hi.
Thanks for the report and sorry for the long delay in replying.

It seems that Apron tried to compile some C++ code when no compiler is detected, to support C++ libraries (that, strangely, are detected even though the C++ compiler is not there...). I hope that #104 should fix the issue.

If you have time to test #104, I would be interested in the results.

**Comment by antoinemine** [comment]
Thank you for you quick response! I will merge the patch then.
