### ISSUE TITLE
Issues with DISEQ constraint?

### ISSUE THREAD

**Issue by DivyaRathore09** [antoinemine/apron#109]
With the following abstract value 
![Screenshot 2024-06-03 at 5 20 42 PM](https://github.com/antoinemine/apron/assets/37830852/651aaf50-490c-4443-987a-58318216d4b3)
performing a meet of the constraint 
![Screenshot 2024-06-03 at 5 21 20 PM](https://github.com/antoinemine/apron/assets/37830852/92dc9f0e-de0d-4166-add3-dcf4206872f9)
of type Tcons1 should technically produce bottom instead, it produces 
![Screenshot 2024-06-03 at 5 22 26 PM](https://github.com/antoinemine/apron/assets/37830852/5671cc16-d1e1-422d-a0b0-00675b0ed6f7)
Am I missing something, or is it some issue?

**Comment by rmonat** [comment]
I think this was covered in #92.
