### ISSUE TITLE
Please add to the README how to run tests

### ISSUE THREAD

**Issue by yurivict** [antoinemine/apron#110]
Commands ```make test``` or ```make check``` don't work.

**Comment by antoinemine** [comment]
There is no `test` nor `check` target in the toplevel `Makfile` (the reason `make test` returns without an error but without doing any action is that there is a directory named `test`, so, `make` thinks the `test` target is already built). There is no plan at the moment to add these targets (but you are welcome to propose a patch in this direction).

Some of the domains do feature tests. How to run them is documented in the `README` file in their respective directory.
