### ISSUE TITLE
Segmentation fault in oct_free

### ISSUE THREAD

**Issue by svenkeidel** [antoinemine/apron#117]
Hi Antione,

I encountered a segmentation fault when the Java garbage-collection thread collects an `Abstract0`. The segmentation fault occurs non-deterministically after I run a large test suite that allocates many managers and abstract domains ([crash.log](https://github.com/user-attachments/files/16452506/hs_err_pid14506.log)):

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f4d859ce257, pid=14506, tid=14515
# JRE version: OpenJDK Runtime Environment (19.0.2+7) (build 19.0.2+7-nixos)
# Java VM: OpenJDK 64-Bit Server VM (19.0.2+7-nixos, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [liboctD.so+0xf257]  oct_free+0x17
...
---------------  T H R E A D  ---------------

Current thread (0x00007f4d8015b3e0):  JavaThread "Finalizer" daemon [_thread_in_native, id=14515, stack(0x00007f4d7ff00000,0x00007f4d80000000)]

Stack: [0x00007f4d7ff00000,0x00007f4d80000000],  sp=0x00007f4d7fffe430,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [liboctD.so+0xf257]  oct_free+0x17

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 2266  apron.Abstract0.finalize()V (0 bytes) @ 0x00007f4d7058c8e0 [0x00007f4d7058c8a0+0x0000000000000040]
J 3571 c2 java.lang.ref.Finalizer.runFinalizer(Ljdk/internal/access/JavaLangAccess;)V java.base@19.0.2 (135 bytes) @ 0x00007f4d705f8df8 [0x00007f4d705f8b40+0x00000000000002b8]
J 4512% c1 java.lang.ref.Finalizer$FinalizerThread.run()V java.base@19.0.2 (39 bytes) @ 0x00007f4d6925f074 [0x00007f4d6925ed00+0x0000000000000374]
v  ~StubRoutines::call_stub 0x00007f4d6ff37cc6
```

Unfortunately, I was not able to reduce this to a minimal example that reproduces the bug. However, the log of the crash is pretty detailed.

**Comment by antoinemine** [comment]
Thank you for your report. I'm not sure what causes the problem yet...

PR #78 is a proposed change to use a more recent interface for finalization. Could you try to run your tests to see if the problem remains with this branch of Apron ?

**Comment by svenkeidel** [comment]
Thanks, I will try as soon as I'm back from vacation next week. I will also prepare a self-included JAR file with the tests so you can reproduce the issue yourself. I can also provide a core dump.

What information would you need to narrow down the issue?

**Comment by svenkeidel** [comment]
I tried #78 and it works great. All segmentation faults and double frees are gone. Furthermore, I did not discover any regressions. In my opinion, #78 would greatly improve the reliability of the Java bindings of Apron :+1:

**Comment by antoinemine** [comment]
OK, I'm merging. The only issue is that it breaks compatibility with Java 8, which does not have the Cleaner interface. I'm not sure how many people still use Java 8...
