### ISSUE TITLE
Segfault after many operations in the taylor1plus domain.

### ISSUE THREAD

**Issue by gavlegoat** [antoinemine/apron#12]
When performing a loop with many `t1p_of_lincons_array` operations, after a while there is a segfault. The bug occurs in `t1p_init_from_manager` and seems to be because `((t1p_internal*)man->internal)->funid` does not point to a valid location anymore. I've created an example that demonstrates the issue [here](https://gist.github.com/gavlegoat/b04782011bab9bc5ab50210d933501fc). I haven't observed the same issue when using `t1p_meet_lincons_array` without calling it from `t1p_of_lincons_array`, so I think the bug specifically concerns meeting with top.

**Comment by gavlegoat** [comment]
After investigating a little more, I found that this occurs because `pr->inputns` is not always resized when it should be in `t1p_nsym_add`, causing an array overflow. I'm happy to submit a pull request with the fix if you'd like.

**Comment by antoinemine** [comment]
Sorry for not answering faster. I'd be interested in a PR to fix this issue, if it's not too late. In case you have a fix for issue #10, I'll be interested as well.

**Comment by kghorbal** [comment]
Yes, indeed. Thanks for the report and the fix.
