### ISSUE TITLE
Java version check broken in 0.9.12 if _JAVA_OPTIONS is set

### ISSUE THREAD

**Issue by Bo98** [antoinemine/apron#21]
The Java version check added in https://github.com/antoinemine/apron/commit/720a18a20f54cb8def2578e79c9f4f6aa8cc9a62 does not work if `_JAVA_OPTIONS` is set.

To reproduce:
1. Run `export _JAVA_OPTIONS="-Duser.language=en"` (or something similar)
2. Run `./configure`
3. Note that `java_version` will be `Picked up _JAVA_OPTIONS: -Duser`.

The first line of `java -version` when the environment variable is set is:

```
Picked up _JAVA_OPTIONS: -Duser.language=en
```

and the following lines as normal.

**Comment by Bo98** [comment]
Also worth noting that `javah` was removed in JDK 10, not 11. `javac -h` will work as far back as JDK 8 however.

**Comment by antoinemine** [comment]
Sorry for the delay.
PR #30 should fix this, with a better detection of the Java version. We use `javac -h` from Java 8 / 1.8.
It should also fix (I hope) a dependency problem in the Java Makefile that caused `make -j` to fail sometimes.
