### ISSUE TITLE
Import improvements & fixes from the other Apron repositories out there

### ISSUE THREAD

**Issue by antoinemine** [antoinemine/apron#3]

**Comment by yakobowski** [comment]
Hi Antoine.

Is this repo destined to be the authoritative one for Apron in the future? It seems that http://apron.cri.ensmp.fr/library/ is trying to switch to Gitlab, and I would like to clarify to which repo I should send PRs to? I have patches to upstream for Windows compilation.

(If the authorative repo is going to be on Gitlab, but with the same history as yours, I will rebase my patch on top of your repo.)

**Comment by antoinemine** [comment]
Hi Boris,
Yes, this is intended to be the authoritative repository for Apron (switching from svn on INRIA Forge to GitHub). You can base your repo on this one and send us pull requests.
