### ISSUE TITLE
inconsistency between the origin expression and the result expression 

### ISSUE THREAD

**Issue by shengfeng** [antoinemine/apron#32]
When I want to reduce the expression ``[| x + y -2 >= 0; x + y > - 3=0|]``, the result of ``tab`` is `[|-3 + 1 * x + 1 * y >= 0|]`, How can I get the origin expression `x + y - 3 >= 0`?
```
let _ =
  let vx = Var.of_string "x" in
  let vy = Var.of_string "y" in
  let env = Environment.make [||] [|vx;vy|] in
  let c = Texpr1.cst env (Coeff.s_of_int 2) in
  let c' = Texpr1.cst env (Coeff.s_of_int 3) in
  let vx' =  Texpr1.var env vx in
  let vy' = Texpr1.var env vy in
  let texpr = Texpr1.binop Add vx' vy' Real Near in
  let texpr1 = Texpr1.binop Sub texpr c Real Near in
  let texpr2 = Texpr1.binop Sub texpr c' Real Near in
  (* let sum' = Texpr1.(Binop(Sub,x2,Cst c,Int,Near)) in *)
  Format.printf "env = %a@." (fun x -> Environment.print x) env;
  Format.printf "expr = %a@." (fun x -> Texpr1.print x) texpr;
  let cons1 = Tcons1.make texpr1 Lincons0.SUPEQ in
  let cons2 = Tcons1.make texpr2 Lincons0.SUPEQ in

  let tab = Tcons1.array_make env 2 in
  Tcons1.array_set tab 0 cons1;
  Tcons1.array_set tab 1 cons2;
  let abs = Abstract1.of_tcons_array manpk env tab in
  let tab' = Abstract1.to_tcons_array manpk abs in
  Format.printf "tab = %a@." (fun x -> Tcons1.array_print x) tab;
  Format.printf "tab1 = %a@." (fun x -> Tcons1.array_print x) tab'
```

**Comment by antoinemine** [comment]
In general, you cannot get the origin expression. `tab1` is not a subset of the constraints in`tab`. It is the result of over-approximating the set of points satisfying the constraints as an abstract element, and then extracting a set of constraints that define this abstract element. In this case, you get a linear constraint that you could simplify by removing the `1*` (the conversion function is not very smart). In general, you may end up with very different constraints.

Can you tell us what you are trying to achieve ?

**Comment by shengfeng** [comment]
I am trying to translate the expression from other language to apron by using ``Texpr1`` and ``Tcons1``. For example, I have the expression such as

 ``x >= 0 -> x - 1 >= 0 -> x - 2 = 0`` 

from Coq. Firstly, I tranlate this expression into 

``[| x > = 0; x - 1 >=0; x - 2 = 0|]``

and create a hastable to record this mapping. Then the result of over-approximating is ``[|x - 2 = 0|]``. As a result, I can rebuild the expression with `x - 2 = 0` by eleminating the redundant constraints. However, the `Linexpr1` doesnot contain the expr such as `Add` or `Mul`. Is there any solution that I can transform an expression from `Tcons1.earray` to `Lincos1.earray` ?

**Comment by antoinemine** [comment]
You could directly convert the abstract element to linear constraints instead of tree constraints, using `Abstract1.to_lincons_array` instead of `Abstract1.to_tcons_array`?

**Comment by shengfeng** [comment]
I maintain a hashtable to record a mapping from Coq to apron, where the key is the constructor `c` of Coq, and the value is a translation of `c` with type ``Tcons1.earray`` in apron. Since I need to compare the over-approximating result with the values in hashtable to eleminate the redundant constraints, and the type of values is ``Tcons1.t``.  I cannot directly convert the abstract element to linear constraints instead of tree constraint. 

For example, I have the expression in Coq such as

``x >= 0 -> x - 1 >= 0 -> x - 2 = 0``

The hashtable is 

``[ (x >= 0, x >= 0); (x - 1 >= 0, x - 1 >= 0); (x - 2 >= 0, x- 2 >=0)]``

The first one of pair is represented with type of ``EConstr.t`` (the type of Coq), and the second one is represented with type of  `Tcons1.t`. Then the result of over-approximating is ``[| - 2 + x = 0 |]`` with type of `Tcons1.earray`. As a result , I cannot directly  match the result in hashtable and get the `x - 2 >= 0 ` in hashtable. How could I solve such problem?
