### ISSUE TITLE
Installs libraries without extension

### ISSUE THREAD

**Issue by yurivict** [antoinemine/apron#38]
plist looks like this:

```
...
lib/avo.idl
lib/libap_pkgrid.
lib/libap_pkgrid.a
lib/libap_pkgrid_debug.
lib/libap_pkgrid_debug.a
lib/libap_ppl.
lib/libap_ppl.a
lib/libap_ppl_debug.
lib/libap_ppl_debug.a
lib/libapron.
lib/libapron.a
lib/libapron_debug.
lib/libapron_debug.a
lib/libavoD.
...
```

**Comment by antoinemine** [comment]
Sorry for the delay...
Looks like `EXT_DLL` is left empty. Should be set to `so` (or possibly `dll`).

Are you using `./configure` (you should) ? If so, can you give me the `./configure` command line you use and the output of the command.

Please also provide your `Makefile.config`, your precise architecture and the complete compilation log.

**Comment by yurivict** [comment]
It turned out that ```configure``` wasn't run.

Now it is fine.

Thank you.
