### ISSUE TITLE
Soname not defined within generated posix shared libraries 

### ISSUE THREAD

**Issue by rmonat** [antoinemine/apron#51]
Shared object libraries can define an `SONAME` field. This is currently not done within apron. Some programs (such as Python's `ctypes` library) may [assume this field is always defined](https://github.com/python/cpython/blob/ccab67ba7901a3012ad66f0ffafac4ea925a1ff0/Lib/ctypes/util.py). Due to a conjunction of bad situation, this may make the `apronpy` interface unable to easily find `libapron.so` on recent Debian-based distribution, see [related issue on apronpy](https://github.com/caterinaurban/apronpy/issues/6)

I guess it should just be a matter of adding `-Wl,-soname,libbar.so` in addition to the `-shared` when calling the compiler to create `libbar.so`. I can do the PR, I just want to be sure I haven't missed a reason to avoid defining this field.

**Comment by antoinemine** [comment]
There's no reason not to specify a soname when linking the shared library. It just did not seem necessary at the time. If it is, we should add it. It should be easy to fix this by changing `CC_APRON_DYLIB` and `CXX_APRON_DYLIB` in `vars.mk`. Note that we already add `-install_name` on MacOS X, which seems to serve a similar purpose on that OS.

I'd be glad if you could provide a PR, though, as I don't have an easy way to check that the fix works.

**Comment by rmonat** [comment]
Great, I'll do that in the coming days.

**Comment by rmonat** [comment]
Closed in #52
