### ISSUE TITLE
Java compiliation incorrect

### ISSUE THREAD

**Issue by baierd** [antoinemine/apron#74]
Greetings,
while trying to compile Apron with Java bindings i noticed that the apron.jar is not working.
The reason is that you package the `.java` files into the `jar`. You need to package the `class` files into the `jar` instead.

Best,
Daniel

**Comment by baierd** [comment]
I have just noticed that the `gmp.jar` suffers from the same problem.

**Comment by antoinemine** [comment]
Is this the same as issue #64? It should have been fixed by #65, which is merged into master.

However, there is no release with this fix yet, you need to compile from master.

**Comment by baierd** [comment]
YES. I've used the latest release version (and i should have mentioned that!)
Thanks for clearing this up!
