### ISSUE TITLE
Uninterpreted Functions

### ISSUE THREAD

**Issue by winnieros** [antoinemine/apron#77]
Hi, I am currently working on my Bachelor thesis to include Apron in JavaSMT at LMU Munich and I am wonderig, if uninterpreted functions are directly implemented in apron? 
Thanks :)

**Comment by antoinemine** [comment]
No, Apron is only for numeric domains. There is support for uninterpreted functions.

**Comment by winnieros** [comment]
You mean "no support"?

**Comment by antoinemine** [comment]
Given that the request is out of scope of the library, I close the issue.
