### ISSUE TITLE
OCaml 5 support

### ISSUE THREAD

**Issue by FeldrinH** [antoinemine/apron#89]
As far as I understand v0.9.14 will support OCaml 5. I'm just opening this as a tracking issue for having a version supporting OCaml 5 published on Opam.

**Comment by antoinemine** [comment]
There is a beta release of Apron 0.9.14 with OCaml 5 support. It has also been submitted to opam.

**Comment by antoinemine** [comment]
Since Apron 0.9.14 supports OCaml5 and it is no longer in beta in Opam, we can close this.
