### ISSUE TITLE
Publishing Apron

### ISSUE THREAD

**Issue by winnieros** [antoinemine/apron#91]
Hello,
we currently try to include Apron in JavaSMT (https://github.com/sosy-lab/java-smt) as a pseudo SMT solver. We would be interested whether you have published the library in an Ivy/Maven repository? And if not, would you be ok if we publish Apron in our Ivy and Maven repositories (in accordance with your license of course)?
Best, Winnie

**Comment by antoinemine** [comment]
Dear Winnie,
Apron is not currently published in an Ivy and Maven repository. I have no objection to you publishing it that way. You would indeed have to keep the licence.
Note that Apron targets mainly applications on static analysis by abstract interpretation. It is not intended to compete with current SMT solvers, and might not be useful in this context (I'd be glad to be proven wrong, though).
The Java API for Apron is less used than the OCaml one. Please feel free to report any bug you would find and propose fixes and improvements.

**Comment by winnieros** [comment]
Thanks for your answer. Yes, the focus of my BA thesis is to find out to which degree Apron can compete with the other solvers and what the exact differences are.

**Comment by winnieros** [comment]
If you are interested I can send you my results. 
Best, Winnie

**Comment by antoinemine** [comment]
Dear Winnie,
Yes, I would be very interested in your results, and your BA thesis manuscript when it is completed!
Best.
